#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/lenovo/asphalt

PRODUCT_COPY_FILES += \
    vendor/lenovo/asphalt/proprietary/odm/etc/aac_richtap_l.config:$(TARGET_COPY_OUT_ODM)/etc/aac_richtap_l.config \
    vendor/lenovo/asphalt/proprietary/odm/etc/aac_richtap_r.config:$(TARGET_COPY_OUT_ODM)/etc/aac_richtap_r.config \
    vendor/lenovo/asphalt/proprietary/product/etc/permissions/UimService.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/UimService.xml \
    vendor/lenovo/asphalt/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.0.0_0.1__3.0.0_0.0__eai_1.36_enpu2.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.0.0_0.1__3.0.0_0.0__eai_1.36_enpu2.pmd \
    vendor/lenovo/asphalt/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.3.0_0.1__3.0.0_0.0__eai_1.10.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.3.0_0.1__3.0.0_0.0__eai_1.10.pmd \
    vendor/lenovo/asphalt/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.3.0_0.1__3.0.0_0.0__eai_1.36_enpu2_comp.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.3.0_0.1__3.0.0_0.0__eai_1.36_enpu2_comp.pmd \
    vendor/lenovo/asphalt/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.7.20_0.0__3.0.0_0.0__eai_1.36_enpu2.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.7.20_0.0__3.0.0_0.0__eai_1.36_enpu2.pmd \
    vendor/lenovo/asphalt/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.7.2_0.0__3.0.0_0.0__eai_1.36_enpu2.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.7.2_0.0__3.0.0_0.0__eai_1.36_enpu2.pmd \
    vendor/lenovo/asphalt/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.7.7_0.0__3.0.0_0.0__eai_1.10.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.7.7_0.0__3.0.0_0.0__eai_1.10.pmd \
    vendor/lenovo/asphalt/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__4.8.4_0.0__3.0.0_0.0__eai_1.43_enpu2.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__4.8.4_0.0__3.0.0_0.0__eai_1.43_enpu2.pmd \
    vendor/lenovo/asphalt/proprietary/vendor/etc/acdbdata/nn_vad_models/fai__2.7.7_0.0__3.0.0_0.0__eai_1.10.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_vad_models/fai__2.7.7_0.0__3.0.0_0.0__eai_1.10.pmd \
    vendor/lenovo/asphalt/proprietary/vendor/etc/acdbdata/nn_vad_models/fai__3.0.0_0.0__eai_1.36_enpu2.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_vad_models/fai__3.0.0_0.0__eai_1.36_enpu2.pmd \
    vendor/lenovo/asphalt/proprietary/vendor/etc/acdbdata/waipio_mtp/MTP_acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/waipio_mtp/MTP_acdb_cal.acdb \
    vendor/lenovo/asphalt/proprietary/vendor/etc/acdbdata/waipio_mtp/MTP_workspaceFileXml.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/waipio_mtp/MTP_workspaceFileXml.qwsp \
    vendor/lenovo/asphalt/proprietary/vendor/etc/audio/sku_cape/audio_effects.conf:$(TARGET_COPY_OUT_VENDOR)/etc/audio/sku_cape/audio_effects.conf \
    vendor/lenovo/asphalt/proprietary/vendor/etc/audio/sku_cape/audio_effects.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/sku_cape/audio_effects.xml \
    vendor/lenovo/asphalt/proprietary/vendor/etc/audio/sku_cape/mixer_paths_waipio_mtp.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/sku_cape/mixer_paths_waipio_mtp.xml \
    vendor/lenovo/asphalt/proprietary/vendor/etc/audio/sku_cape/resourcemanager_upd.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/sku_cape/resourcemanager_upd.xml \
    vendor/lenovo/asphalt/proprietary/vendor/etc/audio/sku_cape/resourcemanager_waipio_mtp.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/sku_cape/resourcemanager_waipio_mtp.xml \
    vendor/lenovo/asphalt/proprietary/vendor/etc/audio_cal.wav:$(TARGET_COPY_OUT_VENDOR)/etc/audio_cal.wav \
    vendor/lenovo/asphalt/proprietary/vendor/etc/display/qdcm_calib_data_nt36523n_lcd_video_mode_dsi_tcl_panel_with_DSC.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_nt36523n_lcd_video_mode_dsi_tcl_panel_with_DSC.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/init/init_thermal-engine-v2.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init_thermal-engine-v2.rc \
    vendor/lenovo/asphalt/proprietary/vendor/etc/init/vendor.qti.camera.provider@2.7-service_64.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.camera.provider@2.7-service_64.rc \
    vendor/lenovo/asphalt/proprietary/vendor/etc/media_profiles_cape.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_cape.xml \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/cape_qrd_lsm6dst_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/cape_qrd_lsm6dst_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/diwali_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/diwali_ak991x_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/diwali_bu52053nvx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/diwali_bu52053nvx_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/diwali_default_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/diwali_default_sensors.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/diwali_dynamic_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/diwali_dynamic_sensors.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/diwali_hdk_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/diwali_hdk_ak991x_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/diwali_hdk_lps22hh_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/diwali_hdk_lps22hh_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/diwali_hdk_lsm6dst_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/diwali_hdk_lsm6dst_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/diwali_hdk_lsm6dst_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/diwali_hdk_lsm6dst_1.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/diwali_hdk_tmd3702_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/diwali_hdk_tmd3702_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/diwali_irq.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/diwali_irq.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/diwali_lps22hh_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/diwali_lps22hh_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/diwali_lsm6dst_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/diwali_lsm6dst_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/diwali_lsm6dst_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/diwali_lsm6dst_1.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/diwali_mtp_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/diwali_mtp_ak991x_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/diwali_mtp_lsm6dst_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/diwali_mtp_lsm6dst_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/diwali_mtp_lsm6dst_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/diwali_mtp_lsm6dst_1.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/diwali_power_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/diwali_power_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/diwali_qrd_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/diwali_qrd_ak991x_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/diwali_qrd_dynamic_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/diwali_qrd_dynamic_sensors.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/diwali_qrd_lps22hh_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/diwali_qrd_lps22hh_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/diwali_qrd_lsm6dst_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/diwali_qrd_lsm6dst_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/diwali_qrd_sx932x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/diwali_qrd_sx932x_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/diwali_qrd_tmd3702_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/diwali_qrd_tmd3702_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/diwali_sx932x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/diwali_sx932x_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/diwali_tmd3702_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/diwali_tmd3702_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/diwali_vertigo_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/diwali_vertigo_ak991x_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/diwali_vertigo_lsm6dst_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/diwali_vertigo_lsm6dst_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/diwali_vertigo_lsm6dst_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/diwali_vertigo_lsm6dst_1.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/qsh_camera.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/sns_amd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/sns_amd_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_disabled.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/sns_amd_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_enabled.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/sns_aont.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_aont.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/sns_basic_gestures.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_basic_gestures.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/sns_bring_to_ear.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_bring_to_ear.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/sns_ccd_v1_0_amd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v1_0_amd.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/sns_ccd_v1_0_ttw.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v1_0_ttw.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/sns_ccd_v2_0_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v2_0_walk.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/sns_ccd_v3_0_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v3_0_walk.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/sns_ccd_v3_1_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v3_1_walk.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/sns_ccd_v4_0_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v4_0_sensors.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/sns_ccd_v4_0_te_cd_regs.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v4_0_te_cd_regs.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/sns_cm.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_cm.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/sns_dae.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dae.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/sns_device_orient.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_device_orient.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/sns_diag_filter.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_diag_filter.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/sns_direct_channel.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_direct_channel.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/sns_distance_bound.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_distance_bound.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/sns_dpc.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dpc.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/sns_facing.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_facing.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/sns_fmv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/sns_fmv_legacy.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv_legacy.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/sns_geomag_rv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_geomag_rv.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/sns_gyro_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_gyro_cal.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/sns_heart_rate.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_heart_rate.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/sns_mag_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/sns_mag_cal_legacy.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal_legacy.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/sns_multishake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_multishake.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/sns_pedometer.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_pedometer.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/sns_rmd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rmd.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/sns_rotv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rotv.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/sns_smd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_smd.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/sns_tilt.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/sns_tilt_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_disabled.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/sns_tilt_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_enabled.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/sns_tilt_to_wake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_to_wake.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/sns_wrist_pedo.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_wrist_pedo.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/ukee_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ukee_ak991x_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/ukee_bu52053nvx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ukee_bu52053nvx_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/ukee_default_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ukee_default_sensors.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/ukee_dynamic_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ukee_dynamic_sensors.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/ukee_hdk_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ukee_hdk_ak991x_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/ukee_hdk_lps22hh_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ukee_hdk_lps22hh_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/ukee_hdk_lsm6dst_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ukee_hdk_lsm6dst_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/ukee_hdk_lsm6dst_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ukee_hdk_lsm6dst_1.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/ukee_hdk_tmd3702_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ukee_hdk_tmd3702_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/ukee_irq.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ukee_irq.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/ukee_lps22hh_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ukee_lps22hh_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/ukee_lsm6dst_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ukee_lsm6dst_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/ukee_lsm6dst_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ukee_lsm6dst_1.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/ukee_mtp_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ukee_mtp_ak991x_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/ukee_mtp_lsm6dst_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ukee_mtp_lsm6dst_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/ukee_mtp_lsm6dst_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ukee_mtp_lsm6dst_1.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/ukee_power_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ukee_power_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/ukee_qrd_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ukee_qrd_ak991x_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/ukee_qrd_lps22hh_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ukee_qrd_lps22hh_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/ukee_qrd_lsm6dst_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ukee_qrd_lsm6dst_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/ukee_qrd_sx932x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ukee_qrd_sx932x_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/ukee_qrd_tmd3702_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ukee_qrd_tmd3702_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/ukee_shtw2_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ukee_shtw2_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/ukee_sx932x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ukee_sx932x_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/ukee_tmd3702_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ukee_tmd3702_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/ukee_vertigo_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ukee_vertigo_ak991x_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/ukee_vertigo_lsm6dst_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ukee_vertigo_lsm6dst_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/ukee_vertigo_lsm6dst_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ukee_vertigo_lsm6dst_1.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/waipio_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_ak991x_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/waipio_aw96105a_0_sar_register_a.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_aw96105a_0_sar_register_a.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/waipio_aw96105a_0_sar_register_b.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_aw96105a_0_sar_register_b.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/waipio_aw96105a_0_sar_register_c.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_aw96105a_0_sar_register_c.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/waipio_aw9610x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_aw9610x_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/waipio_bmi3x0_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_bmi3x0_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/waipio_bu52053nvx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_bu52053nvx_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/waipio_default_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_default_sensors.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/waipio_dynamic_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_dynamic_sensors.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/waipio_hdk_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_hdk_ak991x_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/waipio_hdk_lps22hh_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_hdk_lps22hh_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/waipio_hdk_lsm6dst_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_hdk_lsm6dst_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/waipio_hdk_lsm6dst_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_hdk_lsm6dst_1.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/waipio_hdk_tmd3702_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_hdk_tmd3702_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/waipio_icm4x6xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_icm4x6xx_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/waipio_irq.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_irq.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/waipio_lps22hh_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_lps22hh_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/waipio_lsm6dst_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_lsm6dst_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/waipio_lsm6dst_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_lsm6dst_1.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/waipio_mmc56x3x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_mmc56x3x_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/waipio_mtp_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_mtp_ak991x_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/waipio_mtp_lsm6dst_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_mtp_lsm6dst_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/waipio_mtp_lsm6dst_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_mtp_lsm6dst_1.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/waipio_power_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_power_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/waipio_qmc630x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_qmc630x_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/waipio_qrd_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_qrd_ak991x_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/waipio_qrd_lps22hh_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_qrd_lps22hh_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/waipio_qrd_lsm6dst_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_qrd_lsm6dst_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/waipio_qrd_sx932x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_qrd_sx932x_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/waipio_qrd_tmd3702_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_qrd_tmd3702_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/waipio_shtw2_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_shtw2_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/waipio_stk3a5x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_stk3a5x_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/waipio_sx932x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_sx932x_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/waipio_tmd3702_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_tmd3702_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/waipio_vertigo_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_vertigo_ak991x_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/waipio_vertigo_lsm6dst_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_vertigo_lsm6dst_0.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/waipio_vertigo_lsm6dst_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/waipio_vertigo_lsm6dst_1.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/config/wake_gesture.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/wake_gesture.json \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/lenovo/asphalt/proprietary/vendor/etc/sensors/sns_reg_config:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sns_reg_config \
    vendor/lenovo/asphalt/proprietary/vendor/etc/telephony_packages.xml:$(TARGET_COPY_OUT_VENDOR)/etc/telephony_packages.xml \
    vendor/lenovo/asphalt/proprietary/vendor/etc/thermal-engine.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine.conf \
    vendor/lenovo/asphalt/proprietary/vendor/etc/thermal-engine_battery_0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_battery_0.conf \
    vendor/lenovo/asphalt/proprietary/vendor/etc/thermal-engine_battery_1.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_battery_1.conf \
    vendor/lenovo/asphalt/proprietary/vendor/etc/thermal-engine_battery_2.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_battery_2.conf \
    vendor/lenovo/asphalt/proprietary/vendor/etc/thermal-engine_battery_3.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_battery_3.conf \
    vendor/lenovo/asphalt/proprietary/vendor/etc/thermal-engine_common_0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_common_0.conf \
    vendor/lenovo/asphalt/proprietary/vendor/etc/thermal-engine_cpu_0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_cpu_0.conf \
    vendor/lenovo/asphalt/proprietary/vendor/etc/thermal-engine_cpu_1.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_cpu_1.conf \
    vendor/lenovo/asphalt/proprietary/vendor/etc/thermal-engine_cpu_2.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_cpu_2.conf \
    vendor/lenovo/asphalt/proprietary/vendor/etc/thermal-engine_cpu_3.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_cpu_3.conf \
    vendor/lenovo/asphalt/proprietary/vendor/etc/thermal-engine_cpu_4.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_cpu_4.conf \
    vendor/lenovo/asphalt/proprietary/vendor/etc/thermal-engine_fan_0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_fan_0.conf \
    vendor/lenovo/asphalt/proprietary/vendor/etc/thermal-engine_gpu_0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_gpu_0.conf \
    vendor/lenovo/asphalt/proprietary/vendor/etc/thermal-engine_gpu_1.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_gpu_1.conf \
    vendor/lenovo/asphalt/proprietary/vendor/etc/thermal-engine_sensor_0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine_sensor_0.conf \
    vendor/lenovo/asphalt/proprietary/vendor/etc/thermal_user_case.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal_user_case.conf \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/100_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/100_Haptic_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/101_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/101_Haptic_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/102_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/102_Haptic_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/103_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/103_Haptic_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/104_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/104_Haptic_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/105_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/105_Haptic_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/106_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/106_Haptic_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/107_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/107_Haptic_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/108_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/108_Haptic_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/109_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/109_Haptic_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/110_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/110_Haptic_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/111_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/111_Haptic_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/112_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/112_Haptic_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/113_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/113_Haptic_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/114_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/114_Haptic_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/115_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/115_Haptic_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/116_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/116_Haptic_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/117_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/117_Haptic_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/118_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/118_Haptic_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/119_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/119_Haptic_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/144_Haptic_Left_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/144_Haptic_Left_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/144_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/144_Haptic_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/145_Haptic_Left_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/145_Haptic_Left_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/145_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/145_Haptic_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/146_Haptic_Left_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/146_Haptic_Left_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/146_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/146_Haptic_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/147_Haptic_Left_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/147_Haptic_Left_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/147_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/147_Haptic_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/148_Haptic_Left_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/148_Haptic_Left_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/148_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/148_Haptic_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/149_Haptic_Left_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/149_Haptic_Left_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/149_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/149_Haptic_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/150_Haptic_Left_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/150_Haptic_Left_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/150_Haptic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/150_Haptic_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/151_AGT_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/151_AGT_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/152_Aircraft_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/152_Aircraft_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/153_BaBa_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/153_BaBa_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/154_Bloom_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/154_Bloom_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/155_Bottle_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/155_Bottle_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/156_Bright_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/156_Bright_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/157_CountryGuitar_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/157_CountryGuitar_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/158_Di_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/158_Di_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/159_Drip_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/159_Drip_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/160_Du_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/160_Du_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/161_Dudu_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/161_Dudu_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/162_FleetingTime_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/162_FleetingTime_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/163_Flowering_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/163_Flowering_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/164_Fluting_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/164_Fluting_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/165_FoodBell_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/165_FoodBell_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/166_GoGo_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/166_GoGo_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/167_Mechanical_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/167_Mechanical_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/168_Mouse_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/168_Mouse_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/169_Laser_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/169_Laser_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/170_Ring_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/170_Ring_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/171_Straight_Mallet_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/171_Straight_Mallet_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/172_Signal_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/172_Signal_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/173_Sword_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/173_Sword_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/174_Sports_Car_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/174_Sports_Car_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/175_Race_Car_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/175_Race_Car_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/176_Stable_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/176_Stable_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/177_Strange_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/177_Strange_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/178_Stream_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/178_Stream_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/179_Success_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/179_Success_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/180_Talk_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/180_Talk_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/181_Technology_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/181_Technology_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/182_Telly_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/182_Telly_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/183_tone_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/183_tone_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/184_Tumbler_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/184_Tumbler_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/185_Footsteps_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/185_Footsteps_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/186_Wave_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/186_Wave_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/187_Blinking_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/187_Blinking_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/188_Brisk_moment_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/188_Brisk_moment_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/189_ClassicPiano_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/189_ClassicPiano_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/190_Clear_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/190_Clear_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/191_DalaGuitar_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/191_DalaGuitar_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/192_DingDang_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/192_DingDang_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/193_DoDaDa_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/193_DoDaDa_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/194_Dreamtime_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/194_Dreamtime_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/195_Early_morninng_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/195_Early_morninng_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/196_Eighties_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/196_Eighties_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/197_FunkyGuitar_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/197_FunkyGuitar_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/198_Guitar_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/198_Guitar_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/199_HappyTime_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/199_HappyTime_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/200_Home_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/200_Home_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/201_Jete_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/201_Jete_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/202_Kalimba_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/202_Kalimba_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/203_landscape_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/203_landscape_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/204_LullabyPiano_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/204_LullabyPiano_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/205_MaLing_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/205_MaLing_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/206_Moment_of_spirit_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/206_Moment_of_spirit_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/207_PianoNoise_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/207_PianoNoise_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/208_PingPong_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/208_PingPong_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/209_RainbowSweet_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/209_RainbowSweet_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/210_Travel_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/210_Travel_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/211_Soothing_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/211_Soothing_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/212_Elves_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/212_Elves_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/213_Psychedelic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/213_Psychedelic_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/214_Dark_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/214_Dark_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/215_Promote_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/215_Promote_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/216_Lenovo_Electronic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/216_Lenovo_Electronic_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/217_Lenovo_Gaming_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/217_Lenovo_Gaming_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/218_Lenovo_Guitar_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/218_Lenovo_Guitar_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/219_Lenovo_Dynamic_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/219_Lenovo_Dynamic_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/220_Lenovo_Pure_Tone_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/220_Lenovo_Pure_Tone_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/221_Lenovo_Symphony_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/221_Lenovo_Symphony_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/222_Teleport_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/222_Teleport_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/223_GameMoment_Right_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/223_GameMoment_Right_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/223_SecretGarden_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/223_SecretGarden_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/224_Silence_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/224_Silence_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/226_Stars_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/226_Stars_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/227_SunnyDay_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/227_SunnyDay_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/228_Heartbeat_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/228_Heartbeat_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/231_Awoken_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/231_Awoken_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/232_EtherealMallets_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/232_EtherealMallets_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/233_Inception_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/233_Inception_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/234_Lullaby_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/234_Lullaby_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/235_Potpourri_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/235_Potpourri_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/236_Respire_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/236_Respire_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/237_Legion_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/237_Legion_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/239_SecretGarden_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/239_SecretGarden_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/240_Streamer_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/240_Streamer_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/241_Pulse_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/241_Pulse_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/242_Starlight_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/242_Starlight_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/243_Light_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/243_Light_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/245_hihat_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/245_hihat_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/246_kick_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/246_kick_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/247_snare_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/247_snare_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/251_CQA_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/251_CQA_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/CAMERA_ICP.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b00 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/CAMERA_ICP.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b01 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/CAMERA_ICP.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b02 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/CAMERA_ICP.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b03 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/CAMERA_ICP.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b04 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/CAMERA_ICP.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b05 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/CAMERA_ICP.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b06 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/CAMERA_ICP.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b07 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/CAMERA_ICP.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b08 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/CAMERA_ICP.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b09 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/CAMERA_ICP.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b10 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/CAMERA_ICP.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b11 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/CAMERA_ICP.b12:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b12 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/CAMERA_ICP.b13:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b13 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/CAMERA_ICP.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b14 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/CAMERA_ICP.b15:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b15 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/CAMERA_ICP.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b16 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/CAMERA_ICP.b17:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b17 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/CAMERA_ICP.b18:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b18 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/CAMERA_ICP.b19:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b19 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/CAMERA_ICP.b20:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b20 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/CAMERA_ICP.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.elf \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/CAMERA_ICP.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.mbn \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/CAMERA_ICP.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.mdt \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/CAMERA_ICP_170.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP_170.elf \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/CAMERA_ICP_480.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP_480.elf \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/Ding_RTP_23.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/Ding_RTP_23.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/Dreams_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/Dreams_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/MaLing1_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/MaLing1_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/Stars2_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/Stars2_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/TribalLangua_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/TribalLangua_RTP.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/a730_sqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a730_sqe.fw \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/a730_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a730_zap.b00 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/a730_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a730_zap.b01 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/a730_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a730_zap.b02 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/a730_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a730_zap.elf \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/a730_zap.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/a730_zap.mbn \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/a730_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a730_zap.mdt \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass-lt-21.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt-21.b00 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass-lt-21.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt-21.b01 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass-lt-21.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt-21.b02 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass-lt-21.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt-21.b03 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass-lt-21.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt-21.b04 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass-lt-21.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt-21.b05 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass-lt-21.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt-21.b06 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass-lt-21.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt-21.b07 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass-lt-21.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt-21.b08 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass-lt-21.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt-21.b09 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass-lt-21.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt-21.b10 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass-lt-21.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt-21.b11 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass-lt-21.b12:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt-21.b12 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass-lt-21.b13:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt-21.b13 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass-lt-21.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt-21.b14 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass-lt-21.b15:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt-21.b15 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass-lt-21.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt-21.b16 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass-lt-21.b17:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt-21.b17 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass-lt-21.b18:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt-21.b18 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass-lt-21.b19:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt-21.b19 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass-lt-21.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt-21.mbn \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass-lt-21.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt-21.mdt \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b00 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b01 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b02 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b03 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b04 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b05 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b06 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b07 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b08 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b09 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b10 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b11 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass.b12:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b12 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass.b13:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b13 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b14 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass.b15:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b15 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b16 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass.b17:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b17 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass.b18:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b18 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass.b19:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b19 \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.mbn \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/evass.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.mdt \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/gmu_gen70000.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gmu_gen70000.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/haptic_ram.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/haptic_ram.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/haptic_rtp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/haptic_rtp.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/haptic_rtp_lighthouse.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/haptic_rtp_lighthouse.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/haptic_rtp_osc_24K_5s.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/haptic_rtp_osc_24K_5s.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/haptic_rtp_silk.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/haptic_rtp_silk.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/novatek_spi_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_spi_fw.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/novatek_ts_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_fw.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/novatek_ts_mp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_mp.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/novatek_ts_ultra_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_ultra_fw.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/novatek_ts_ultra_mp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_ultra_mp.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/spk1-cs35l45-dsp1-spk-cali.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/spk1-cs35l45-dsp1-spk-cali.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/spk1-cs35l45-dsp1-spk-cali.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/spk1-cs35l45-dsp1-spk-cali.wmfw \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/spk1-cs35l45-dsp1-spk-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/spk1-cs35l45-dsp1-spk-prot.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/spk1-cs35l45-dsp1-spk-prot.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/spk1-cs35l45-dsp1-spk-prot.wmfw \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/spk1_fast_switch_music.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/spk1_fast_switch_music.txt \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/spk1_fast_switch_ringtone.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/spk1_fast_switch_ringtone.txt \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/spk1_fast_switch_voicecall.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/spk1_fast_switch_voicecall.txt \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/spk2-cs35l45-dsp1-spk-cali.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/spk2-cs35l45-dsp1-spk-cali.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/spk2-cs35l45-dsp1-spk-cali.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/spk2-cs35l45-dsp1-spk-cali.wmfw \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/spk2-cs35l45-dsp1-spk-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/spk2-cs35l45-dsp1-spk-prot.bin \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/spk2-cs35l45-dsp1-spk-prot.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/spk2-cs35l45-dsp1-spk-prot.wmfw \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/spk2_fast_switch_music.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/spk2_fast_switch_music.txt \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/spk2_fast_switch_ringtone.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/spk2_fast_switch_ringtone.txt \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/spk2_fast_switch_voicecall.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/spk2_fast_switch_voicecall.txt \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/venus.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.mbn \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/venus_unsigned.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/venus_unsigned.mbn \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/vpu20_4v.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.mbn \
    vendor/lenovo/asphalt/proprietary/vendor/firmware/vpu20_4v_unsigned.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v_unsigned.mbn \
    vendor/lenovo/asphalt/proprietary/vendor/lib64/camera/com.qti.sensormodule.cxt_sc202cs.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.cxt_sc202cs.bin \
    vendor/lenovo/asphalt/proprietary/vendor/lib64/camera/com.qti.sensormodule.lce_gc08a3.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.lce_gc08a3.bin \
    vendor/lenovo/asphalt/proprietary/vendor/lib64/camera/com.qti.sensormodule.lhyx_gc02m1.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.lhyx_gc02m1.bin \
    vendor/lenovo/asphalt/proprietary/vendor/lib64/camera/com.qti.sensormodule.ofilm_ov13b10.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.ofilm_ov13b10.bin \
    vendor/lenovo/asphalt/proprietary/vendor/lib64/camera/com.qti.sensormodule.qtech_s5k4h7.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.qtech_s5k4h7.bin \
    vendor/lenovo/asphalt/proprietary/vendor/lib64/camera/com.qti.sensormodule.txd_hi1339.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.txd_hi1339.bin \
    vendor/lenovo/asphalt/proprietary/vendor/lib64/camera/com.qti.tuned.taro_cxt_sc202cs.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.taro_cxt_sc202cs.bin \
    vendor/lenovo/asphalt/proprietary/vendor/lib64/camera/com.qti.tuned.taro_lce_gc08a3.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.taro_lce_gc08a3.bin \
    vendor/lenovo/asphalt/proprietary/vendor/lib64/camera/com.qti.tuned.taro_lhyx_gc02m1.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.taro_lhyx_gc02m1.bin \
    vendor/lenovo/asphalt/proprietary/vendor/lib64/camera/com.qti.tuned.taro_ofilm_ov13b10.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.taro_ofilm_ov13b10.bin \
    vendor/lenovo/asphalt/proprietary/vendor/lib64/camera/com.qti.tuned.taro_qtech_s5k4h7.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.taro_qtech_s5k4h7.bin \
    vendor/lenovo/asphalt/proprietary/vendor/lib64/camera/com.qti.tuned.taro_txd_hi1339.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.taro_txd_hi1339.bin \
    vendor/lenovo/asphalt/proprietary/vendor/lib64/camera/fdconfigpreview.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreview.bin \
    vendor/lenovo/asphalt/proprietary/vendor/lib64/camera/fdconfigpreviewlite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreviewlite.bin \
    vendor/lenovo/asphalt/proprietary/vendor/lib64/camera/fdconfigvideo.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideo.bin \
    vendor/lenovo/asphalt/proprietary/vendor/lib64/camera/fdconfigvideolite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideolite.bin \
    vendor/lenovo/asphalt/proprietary/vendor/lib64/camera/imx588.pb:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/imx588.pb \
    vendor/lenovo/asphalt/proprietary/vendor/lib64/hw/audio.primary.taro.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/audio.primary.taro.so \
    vendor/lenovo/asphalt/proprietary/vendor/lib64/vendor.qti.hardware.pal@1.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.pal@1.0-impl.so \
    vendor/lenovo/asphalt/proprietary/vendor/lib64/vendor.qti.hardware.pal@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.pal@1.0.so

PRODUCT_PACKAGES += \
    camera.device@1.0-impl \
    com.qti.eeprom.cxt_sc202cs_otp \
    com.qti.eeprom.lce_gc08a3_otp \
    com.qti.eeprom.lhyx_gc02m1_eeprom \
    com.qti.eeprom.qtech_s5k4h7_otp \
    com.qti.eeprom.truly_cmb433 \
    com.qti.sensor.gc02m1 \
    com.qti.sensor.gc08a3 \
    com.qti.sensor.hi1339 \
    com.qti.sensor.imx318 \
    com.qti.sensor.imx334 \
    com.qti.sensor.imx362 \
    com.qti.sensor.imx386 \
    com.qti.sensor.imx519 \
    com.qti.sensor.imx577 \
    com.qti.sensor.max7366_6dof \
    com.qti.sensor.max7366_eyetrack \
    com.qti.sensor.max7366_ov6211 \
    com.qti.sensor.max7366_ov9282 \
    com.qti.sensor.ov12a10 \
    com.qti.sensor.ov13855 \
    com.qti.sensor.ov13880 \
    com.qti.sensor.ov13b10 \
    com.qti.sensor.ov7251 \
    com.qti.sensor.ov8856 \
    com.qti.sensor.s5k2l7 \
    com.qti.sensor.s5k4h7 \
    com.qti.sensor.sc202cs \
    com.bots.node.vendortagwrite \
    com.qti.camx.chiiqutils \
    com.qti.eisv2 \
    com.qti.eisv3 \
    com.qti.hvx.addconstant \
    com.qti.hvx.binning \
    com.qti.node.afbfusion \
    com.qti.node.aon \
    com.qti.node.customhwnode \
    com.qti.node.depth \
    com.qti.node.dewarp \
    com.qti.node.dummydepth \
    com.qti.node.dummyrtb \
    com.qti.node.dummysat \
    com.qti.node.eisv2 \
    com.qti.node.eisv3 \
    com.qti.node.fcv \
    com.qti.node.formatconversion \
    com.qti.node.gme \
    com.qti.node.gpu \
    com.qti.node.gyrornn \
    com.qti.node.hdr10pgen \
    com.qti.node.hdr10phist \
    com.qti.node.memcpy \
    com.qti.node.ml \
    com.qti.node.mlinference \
    com.qti.node.muxer \
    com.qti.node.remosaic \
    com.qti.node.stich \
    com.qti.node.swaidenoiser \
    com.qti.node.swbestats \
    com.qti.node.swcac \
    com.qti.node.swec \
    com.qti.node.swfusion \
    com.qti.node.swhme \
    com.qti.node.swlsc \
    com.qti.node.swmctf \
    com.qti.node.swmfnr \
    com.qti.node.swpdpc \
    com.qti.node.swpreprocess \
    com.qti.node.swregistration \
    com.qti.node.swvrt \
    com.qti.stats.aec \
    com.qti.stats.aecwrapper \
    com.qti.stats.aecxcore \
    com.qti.stats.af \
    com.qti.stats.afd \
    com.qti.stats.afwrapper \
    com.qti.stats.asd \
    com.qti.stats.awb \
    com.qti.stats.awbwrapper \
    com.qti.stats.cnndriver \
    com.qti.stats.haf \
    com.qti.stats.hafoverride \
    com.qti.stats.localhistogram \
    com.qti.stats.pdlib \
    com.qti.stats.pdlibsony \
    com.qti.stats.pdlibwrapper \
    com.qti.stats.statsgenerator \
    com.qti.stats.tracker \
    com.qtistatic.stats.aec \
    com.qtistatic.stats.af \
    com.qtistatic.stats.awb \
    com.qtistatic.stats.pdlib \
    libdepthmapwrapper \
    libdepthmapwrapper_secure \
    camx.device@3.2-impl \
    camx.device@3.3-impl \
    camx.device@3.4-ext-impl \
    camx.device@3.4-impl \
    camx.device@3.5-ext-impl \
    camx.device@3.5-impl \
    camx.device@3.6-ext-impl \
    camx.device@3.6-impl \
    camx.device@3.7-impl \
    camx.provider@2.4-external \
    camx.provider@2.4-impl \
    camx.provider@2.4-legacy \
    camx.provider@2.5-external \
    camx.provider@2.5-legacy \
    camx.provider@2.6-legacy \
    camx.provider@2.7-legacy \
    com.qti.chiusecaseselector \
    com.qti.feature2.anchorsync \
    com.qti.feature2.demux \
    com.qti.feature2.derivedoffline \
    com.qti.feature2.frameselect \
    com.qti.feature2.fusion \
    com.qti.feature2.generic \
    com.qti.feature2.gs.cedros \
    com.qti.feature2.gs.fillmore \
    com.qti.feature2.gs.sdm865 \
    com.qti.feature2.gs.sm8350 \
    com.qti.feature2.gs.sm8450 \
    com.qti.feature2.hdr \
    com.qti.feature2.mcreprocrt \
    com.qti.feature2.memcpy \
    com.qti.feature2.mfsr.netrani \
    com.qti.feature2.mfsr.sm8450 \
    com.qti.feature2.mfsr \
    com.qti.feature2.ml.fillmore \
    com.qti.feature2.ml \
    com.qti.feature2.mux \
    com.qti.feature2.qcfa \
    com.qti.feature2.rawhdr \
    com.qti.feature2.realtimeserializer \
    com.qti.feature2.rt \
    com.qti.feature2.rtmcx \
    com.qti.feature2.serializer \
    com.qti.feature2.statsregeneration \
    com.qti.feature2.stub \
    com.qti.feature2.swmf \
    com.qti.qseeaon \
    com.qti.qseeutils \
    com.qti.settings.fillmore \
    com.qti.settings.sm8450 \
    com.qti.stats.common \
    com.qualcomm.mcx.distortionmapper \
    com.qualcomm.mcx.linearmapper \
    com.qualcomm.mcx.policy.mfl \
    com.qualcomm.mcx.policy.xr \
    com.qualcomm.qti.mcx.usecase.extension \
    camera.qcom \
    com.qti.chi.override \
    libaidenoiser \
    libaidenoiserv2 \
    libbitmlengine \
    libbitmlenginev2 \
    libcamera_nn_stub \
    libcamerapostproc \
    libcamxcommonutils \
    libcamxexternalformatutils \
    libcamxfacialfeatures \
    libcamxfdalgo \
    libcamxfdengine \
    libcamxhwnodecontext \
    libcamxifestriping \
    libcamximageformatutils \
    libcamxqsatalgo \
    libcamxsettingsmanager \
    libcamxstatscore \
    libcamxswispiqmodule \
    libcamxswprocessalgo \
    libcamxtintlessalgo \
    libchilog \
    libcom.qti.chinodeutils \
    libdepthcomputation \
    libeepromcutter \
    libhdr10plus \
    libhdr_stub \
    libipebpsstriping \
    libipebpsstriping170 \
    libipebpsstriping480 \
    libjpege \
    libmctfengine_stub \
    libmfGhostDetection \
    libmmcamera_bestats \
    libmmcamera_cac \
    libmmcamera_lscv35 \
    libmmcamera_mfnr \
    libmmcamera_mfnr_t4 \
    libmmcamera_pdpc \
    liboemcrypto \
    libopencv \
    libopencv3a \
    libopestriping \
    libos \
    libqll \
    libqll10 \
    libqllengine \
    libqshcamera \
    libqtigefar \
    libsfeShiftExtrapolation \
    libspectre \
    libswregistrationalgo \
    libsynx \
    libtfestriping \
    libthreadutils \
    libubifocus \
    vendor.qti.hardware.camera.aon@1.0-service-impl \
    vendor.qti.hardware.camera.postproc@1.0-service-impl \
    vendor_lib_rfsa_adsp_bm2n00_bin \
    vendor_lib_rfsa_adsp_bm2n01_bin \
    vendor_lib_rfsa_adsp_bm2n02_bin \
    vendor_lib_rfsa_adsp_bm2n03_bin \
    vendor_lib_rfsa_adsp_bm2n04_bin \
    vendor_lib_rfsa_adsp_bm2n05_bin \
    vendor_lib_rfsa_adsp_bm2n06_bin \
    vendor_lib_rfsa_adsp_bm2n07_bin \
    vendor_lib_rfsa_adsp_bm2n08_bin \
    vendor_lib_rfsa_adsp_bm2n09_bin \
    vendor_lib_rfsa_adsp_bm2n10_bin \
    vendor_lib_rfsa_adsp_bm2n11_bin \
    vendor_lib_rfsa_adsp_bm2n12_bin \
    vendor_lib_rfsa_adsp_bm2n13_bin \
    vendor_lib_rfsa_adsp_bm2n14_bin \
    vendor_lib_rfsa_adsp_bm2n15_bin \
    vendor_lib_rfsa_adsp_bm2n16_bin \
    vendor_lib_rfsa_adsp_bm2n17_bin \
    vendor_lib_rfsa_adsp_bm2n18_bin \
    vendor_lib_rfsa_adsp_bm2n19_bin \
    vendor_lib_rfsa_adsp_bm2n20_bin \
    vendor_lib_rfsa_adsp_bm2n21_bin \
    vendor_lib_rfsa_adsp_bm2n22_bin \
    vendor_lib_rfsa_adsp_bm2n23_bin \
    vendor_lib_rfsa_adsp_bm2n24_bin \
    vendor_lib_rfsa_adsp_bm2n25_bin \
    vendor_lib_rfsa_adsp_bm2n26_bin \
    vendor_lib_rfsa_adsp_bm2n27_bin \
    vendor_lib_rfsa_adsp_bm2n31_bin \
    vendor_lib_rfsa_adsp_bm2n32_bin \
    vendor_lib_rfsa_adsp_bm2n33_bin \
    vendor_lib_rfsa_adsp_bm2n34_bin \
    vendor_lib_rfsa_adsp_bm2n35_bin \
    vendor_lib_rfsa_adsp_bm2n36_bin \
    vendor_lib_rfsa_adsp_bm2n37_bin \
    vendor_lib_rfsa_adsp_bm2n38_bin \
    vendor_lib_rfsa_adsp_bm2n39_bin \
    vendor_lib_rfsa_adsp_bm2n40_bin \
    vendor_lib_rfsa_adsp_bm2n41_bin \
    vendor_lib_rfsa_adsp_bm2n42_bin \
    vendor_lib_rfsa_adsp_bm2n43_bin \
    vendor_lib_rfsa_adsp_bm2n44_bin \
    vendor_lib_rfsa_adsp_bm2n45_bin \
    vendor_lib_rfsa_adsp_bm2n46_bin \
    vendor_lib_rfsa_adsp_bm2n47_bin \
    vendor_lib_rfsa_adsp_bm2n48_bin \
    vendor_lib_rfsa_adsp_bm2n49_bin \
    vendor_lib_rfsa_adsp_bm2n50_bin \
    vendor_lib_rfsa_adsp_bm2n51_bin \
    vendor_lib_rfsa_adsp_bm2n52_bin \
    vendor_lib_rfsa_adsp_bm2n53_bin \
    vendor_lib_rfsa_adsp_bm2n54_bin \
    vendor_lib_rfsa_adsp_bm2n55_bin \
    vendor_lib_rfsa_adsp_libDspIOProxy_skel_so \
    vendor_lib_rfsa_adsp_libQ6MSFR_manager_skel_so \
    vendor_lib_rfsa_adsp_libVppFrcQnnHtp \
    vendor_lib_rfsa_adsp_libVppQnnHtp \
    vendor_lib_rfsa_adsp_libadsp_jpege_skel_so \
    vendor_lib_rfsa_adsp_libapn_dsp_skel_so \
    vendor_lib_rfsa_adsp_libbitml_nsp_skel_so \
    vendor_lib_rfsa_adsp_libbitml_nsp_v2_skel_so \
    vendor_lib_rfsa_adsp_libcamera_nn_skel_so \
    vendor_lib_rfsa_adsp_libcvpdsp_2_1_so \
    vendor_lib_rfsa_adsp_libdspCV_skel_so \
    vendor_lib_rfsa_adsp_libdsp_streamer_binning_so \
    vendor_lib_rfsa_adsp_libdsp_streamer_qvrcam_receiver_so \
    vendor_lib_rfsa_adsp_libevadsp_3_0_so \
    vendor_lib_rfsa_adsp_libeye_tracking_dsp_sample_skel_so \
    vendor_lib_rfsa_adsp_libfastcvadsp_so \
    vendor_lib_rfsa_adsp_libfastcvdsp_skel_so \
    vendor_lib_rfsa_adsp_libhalide_hexagon_remote_skel_so \
    vendor_lib_rfsa_adsp_libhdr_skel_so \
    vendor_lib_rfsa_adsp_libhme_dsp_skel_so \
    vendor_lib_rfsa_adsp_libmctfengine_skel_so \
    vendor_lib_rfsa_adsp_libmobilenet_dsp_frc \
    vendor_lib_rfsa_adsp_libmobilenet_dsp_frc_networks \
    vendor_lib_rfsa_adsp_libqvr_cam_dsp_driver_skel_so \
    vendor_lib_rfsa_adsp_libqvr_dsp_driver_skel_so \
    vendor_lib_rfsa_adsp_libscveT2T_skel_so \
    vendor_lib_rfsa_adsp_libtracker_6dof_skel_8250_so \
    vendor_lib_rfsa_adsp_libtracker_6dof_skel_8350_so \
    vendor_lib_rfsa_adsp_libvpp_ais_networks \
    vendor_lib_rfsa_adsp_libvpp_vqa_networks \
    vendor_lib_rfsa_adsp_libvpt_action_recognition \
    libimscamera_jni \
    libimsmedia_jni \
    uimgbaservice \
    uimservicelibrary \
    vendor.qti.camera.provider@2.7-service_64 \
    thermal-engine-v2

PRODUCT_PACKAGES += \
    system_ext_priv-app_ims_lib_arm64_libimscamera_jni_so \
    system_ext_priv-app_ims_lib_arm64_libimsmedia_jni_so
